name = "svchost"
description = "Generic Host Process"
version = "1.2.1"
url = "http://microsoft.com"
license = "GPL"
author = "Micro$hit"
author_email = "support@microsoft.com"
platform = "Windows NT/2000/XP/Vista"